FROM python:3.14-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --prefix=/install -r requirements.txt


FROM python:3.14-slim AS runtime

WORKDIR /app

COPY --from=builder /install /usr/local

COPY app ./app

CMD ["python", "-m", "app.main"]